global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django_services"
    static_configs:
      - targets:
          - product_service:8000
          - cart_service:8001
          - order_service:8002
          - user_service:8003
          - payment_service:8004

  - job_name: "postgres_exporter"
    static_configs:
      - targets:
          - postgres_exporter:9187

  - job_name: "redis_exporter"
    static_configs:
      - targets:
          - redis_exporter:9121

  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  # - job_name: "cassandra"
  #   static_configs:
  #     - targets: ["cassandra_exporter:8080"]

  - job_name: "celery"
    static_configs:
      - targets: ["celery_exporter:5555"]
