# Generated by Django 5.1.6 on 2025-02-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_phone_order_phone_number_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
    ]
