# Generated by Django 5.1.6 on 2025-02-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
